### ISSUE TITLE
Feature Request: Abstract and review

### ISSUE THREAD

**Issue by creativefibro** [MichaBrugger/booksidian_plugin#10]
This is my template I have set up:
`# {{title}}
Subtitle:: {{subtitle}}
series {{series}}
![Cover]({{cover}})

## 📨 Additional Metadata

🏷 **Tags**

- 🗂Type::   #source/book📚
- 🗣 Subject::
- 🌍Area::
- 🏁Status::
- 💻Platform::
- 📆dates:: {{datePublished}} (Published) {{dateRead}} Read
- 👤author:: {{author}}
- 👨‍👩‍👧‍👦 people::
- ⭐ rating::
`
I leave the rating in the front matter because I swap it to a star system in the metadata. Would it be remotely possible for there to be a field for the Abstract blurb.  At the moment I am copying them over one by one but it would be amazing if the could be brought in. The [Chrome extension for booksidian](https://chrome.google.com/webstore/detail/booksidian/aegbimnoohfodebkjojbabcfkinbjink)  uses the abstract field so I'm assuming it is available for anyone to use. Thank you in advance.

**Comment by MichaBrugger** [comment]
Hi there. I wasn't actually aware that there is a chrome extension with the same name, thanks for sharing that.

Unfortunately, these two tools work very differently. My plugin is using the RSS feed, which makes it possible to collect all items from any shelf, at the cost of the available information being rather limited. The chrome extension on the other hand is (I assume, I don't have access to the code base) scraping the HTML directly from the page, which is also why you have to do them 1 by 1 (you could technically do this on a bigger scale too, but that's kind of a legal grey area).

You can prettify the available information of your RSS-feed [here](https://codebeautify.org/rssviewer). So it should be easy to see what information is available. Just click _load url_ and enter your RSS-url there. I hope that helps and please let me know if there is anything I should add 👍🏼

**Comment by creativefibro** [comment]
I had a look at the selection and it would be good to have the review data. I am currently copying this into my My Thoughts heading. I tried adding {{review}} on the off chance but it added {{review}} as it was. I guess you have to create a field for it to do that. Thanks

**Comment by MichaBrugger** [comment]
Can do! I'll add the review field on the next patch 👍🏼

**Comment by zacharyw** [comment]
@creativefibro Book descriptions and user reviews are included as of 3.0.1.
