### ISSUE TITLE
Sync Issues

### ISSUE THREAD

**Issue by creativefibro** [MichaBrugger/booksidian_plugin#11]
I am having problems again with syncing. I have made no changed at the Obsidian end. All I am doing is going through my GoodReads Books and adding to-obsidian (which is my import folder) to small collections. The biggest has been about 12 books. I'm finding it will do a batch. Then when I try to do the next - maybe ten mins later approximately. When I go to sync nothing happens. 

I don't know if this is the plugin or does it take a while for the Goodreads RSS to know that a new shelf has been added at their end? 

Update: I tested this out and changed my sync shelf to a long established shelf with three books on and that worked. I don't know how long would be best to leave it between adding the shelf and doing the sync? Thanks

**Comment by MichaBrugger** [comment]
To be honest, there is nothing I can do about that. It takes some time for Goodreads to upgrade their feed, but I unfortunately don't know how much that is.
