### ISSUE TITLE
cannot enable the plugin on Android app.

### ISSUE THREAD

**Issue by MrRobot0707** [MichaBrugger/booksidian_plugin#15]
Any solution? I have the rss link but can't enable the plugin on Android app.

![Screenshot_2022-08-10-21-07-07-002_md obsidian](https://user-images.githubusercontent.com/69039494/183948167-a08e3d12-d61c-447c-a29c-988b83924ad9.jpg)

**Comment by zacharyw** [comment]
I get the same thing on iOS, but I can't reproduce it on the obsidian mobile emulator, so I'm not sure how to debug it.

**Comment by MichaBrugger** [comment]
@zacharyw, my best guess would be that the `rss-parser` causes it to crash on mobile (based on [this](https://marcus.se.net/obsidian-plugin-docs/testing/mobile-devices#node-and-electron-apis)). Assuming that the emulator has access to the Node API, this might also explain why the bug doesn't occur when testing on a desktop.

**Comment by zacharyw** [comment]
Sounds like the most straightforward solution is to just make it a desktop only plugin.

**Comment by zacharyw** [comment]
Made desktop only in 0.3.6.
