### ISSUE TITLE
Add plot option

### ISSUE THREAD

**Issue by AriesOdyssey** [MichaBrugger/booksidian_plugin#17]
Hey man, I love this plugin!
I'm very lazy and I'd love for the plot to be an option too. Is this possible? 

Also I noticed that pages was not in the available fields(/placeholders) but it is possible to call it (It works when I sync) and i also saw u wrote code for it. Maybe add it so people don't miss it?

**Comment by zacharyw** [comment]
Hello @AriesOdyssey ! I added pages and the book description (aka the plot) if you update to the latest version.
