### ISSUE TITLE
Categorization of shelves

### ISSUE THREAD

**Issue by Jimgeroman** [MichaBrugger/booksidian_plugin#18]
When i sync all books, to an empty folder, the field for shelves populates correctly for the shelves: to-read, and currently-reading, but is left blank for all books in the read shelf.

**Comment by PieterDeKruiff** [comment]
Can you provide screenshots of your settings and your read shelf? It works fine for me with my setup.

**Comment by PieterDeKruiff** [comment]
> Add saved reply

Can you provide screenshots of your settings and your read shelf? It works fine for me with my setup.

**Comment by Jimgeroman** [comment]
No problem, have just tried in a fresh vault with stock settings and only the booksidian plugin enabled. Ive manually changed it in my working vault just thought it was odd behaviour. Overall awesome plugin though, really appreciate it.

Thanks
James

[Screenshot 2022-12-11 at 8.27.54 pm.png][Screenshot 2022-12-11 at 8.29.28 pm.png][Screenshot 2022-12-11 at 8.31.27 pm.png][Screenshot 2022-12-11 at 8.31.30 pm.png][Screenshot 2022-12-11 at 8.27.26 pm.png][Screenshot 2022-12-11 at 8.28.03 pm.png]

On 11 Dec 2022, at 8:21 pm, Piteter ***@***.***> wrote:



Can you provide screenshots of your settings and your read shelf? It works fine for me with my setup.

**Comment by zacharyw** [comment]
@Jimgeroman Should be resolved as of the 3.0.1 release!
