### ISSUE TITLE
Books with special characters are not created

### ISSUE THREAD

**Issue by Kastan42** [MichaBrugger/booksidian_plugin#19]
If the book has a character, that is not supported by the filesystem for files (typically `? : * / \ " |`), the file is never created if it should appear in the file name.

For example if I have in the shelve this book: https://www.goodreads.com/book/show/21413662-what-if-serious-scientific-answers-to-absurd-hypothetical-questions and want to have the file named `{{title}}`, it is never downloaded.

I suggest create a setting (with default to `-`), for character to replace these special ones, so the file can be created.

Thank you!

**Comment by riccardopinto** [comment]
Hello @MichaBrugger , I have a local PR to fix this issue and add a couple of unit tests. Can I create a pull request? :)

PS: it's my first issue in typescript so... be nice! :D

**Comment by zacharyw** [comment]
Fixed in https://github.com/MichaBrugger/booksidian_plugin/pull/23

**Comment by zacharyw** [comment]
Fixed in https://github.com/MichaBrugger/booksidian_plugin/pull/23
