### ISSUE TITLE
Reaching out, interested in supporting the project

### ISSUE THREAD

**Issue by zacharyw** [MichaBrugger/booksidian_plugin#22]
Hello @MichaBrugger ! Thanks for the great work on this plugin.

If you're still around and interested in getting some help with it, I have a few features I've implemented on a personal fork: https://github.com/zacharyw/booksidian_plugin/commit/717db155857a14bf54792bd58495fcfaf9a09eb3

1. Automatic syncing
2. Option to overwrite existing notes (so that changes in Goodreads, like adding a rating to a book that's already been synced will be picked up)

I actually forked off of @riccardopinto 's open PR to pick up their filename fixes. Initially I was just going to make some changes for personal use but I'd like to get them into the main plugin if possible.

**Comment by zacharyw** [comment]
I opened https://github.com/MichaBrugger/booksidian_plugin/pull/23 that bundles together both PR's, if you're interested 👍

**Comment by MichaBrugger** [comment]
Hi there @zacharyw and @riccardopinto

Thanks so much for reaching out! It's really nice to hear that people still find value in the plugin and even more that there are people interested in continuing its development. While I stubbornly refuse to admit it to myself, the truth is that I haven't really found time for the project in months (sorry for that @riccardopinto).

I'd love for the plugin to continue to add value to some peoples lives. So, long story short: Would you be interested in me adding you as collaborators? This way I wouldn't be the bottleneck and you guys could continue to add your ideas and create value for the other users out there. Furthermore, this would probably be easier and less confusing for the users compared to getting a fork approved by the Obsidian devs and deleting this repo.

If you guys are interested in that, I'd be happy to add you and own it together (feel free to add yourselves as creators of course).

**Comment by riccardopinto** [comment]
Cool, thanks! I would be interested in obsidian development too, but I am
not experienced enough as typescript programmer. I can contribute
occasionally to some PRs though :)

Il gio 13 lug 2023, 16:24 Zachary Wright ***@***.***> ha
scritto:

**Comment by MichaBrugger** [comment]
Perfect, I added you both as collaborators 🙌🏼 

@zacharyw, the Obsidian doc's are generally really nice and if something isn't alright the devs are super friendly too. You can find pretty much all relevant links in the Obsidian-Sample-Plugin (the one from where this plugin has been forked). I hope that helps :)

And @riccardopinto, don't worry too much. Ultimately, this is an open source project and we're all doing it for fun or to learn something new, so you're in good company :)
