### ISSUE TITLE
A link back to Goodreads

### ISSUE THREAD

**Issue by creativefibro** [MichaBrugger/booksidian_plugin#27]
I was just thinking it would be really helpful if there was a way to add a link back to the Goodreads page from your book note, A link within the page would be better than in the Yaml so you can click straight through.

I don't know if that would be too complicated though...

**Comment by zacharyw** [comment]
This is a good idea! The book `id` is actually already available to use within the book content, but I will add it to the frontmatter list so it's more obvious.

Using that id, you can create a link back to goodreads by doing:

```
https://www.goodreads.com/book/show/{{id}}
```

Id will show up in the frontmatter in update 0.3.6, but you can use it to form a link in the current version.

**Comment by MichaBrugger** [comment]
This is an excellent idea! And really thank you @zacharyw for the fast/clean implementation of this and all the other great additions over the past week! It's amazing having you on board!
