### ISSUE TITLE
Incorrect shelf data being pulled through

### ISSUE THREAD

**Issue by PerformedShelf** [MichaBrugger/booksidian_plugin#28]
When syncing notes from my feed, some notes come through with the correct bookshelves but others come with additional bookshelves that they are not a part of on my goodreads. I have my goodreads shelf set up as an exclusive shelf so that 'read' or 'to-read' should not apply to any of those books, yet when I sync them to Obsidian they include 'to-read'.

![image](https://github.com/MichaBrugger/booksidian_plugin/assets/18646619/9f48fb0f-d31c-46ad-a0c1-6683c21d882d)

![image](https://github.com/MichaBrugger/booksidian_plugin/assets/18646619/448370ea-8fed-4651-8720-2bf5ba9f6d43)

It happens whether the book is on an exclusive shelf, and it even happens when changing the books to the 'read' shelf on Goodreads.

**Comment by PerformedShelf** [comment]
It actually fixes if you edit each book to go on to the 'to-read' shelf, then put them on the 'read' shelf before bringing them back to the exclusive shelf. Goodreads problem I think.

**Comment by husjon** [comment]
Closing the issue, please do feel free to re-open if the issue persists.
