### ISSUE TITLE
{{cover}} attribute no longer working

### ISSUE THREAD

**Issue by Sciencegenie7** [MichaBrugger/booksidian_plugin#32]
The {{cover}} attribute is no longer being parsed correctly by Obsidian. Maybe it's a result of recent changes to Obsidian?

I get this:
`![Cover](https:&#x2F;&#x2F;i.gr-assets.com&#x2F;images&#x2F;S&#x2F;compressed.photo.goodreads.com&#x2F;books&#x2F;1675653942l&#x2F;60766189._SY475_.jpg)`

Instead of this:
`![Cover](https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1675653942i/60766189.jpg)`

**Comment by creativefibro** [comment]
I've pulled my newest books in and this also happened to me.

**Comment by benaustin** [comment]
For a workaround

You can replace the Unicode Hex Character \&#x2F;  with the forward slash / and replace all. 
![image](https://github.com/MichaBrugger/booksidian_plugin/assets/3310950/99dd8d87-6e37-47c3-845b-c3868dbf400b)

**Comment by MartinP7r** [comment]
I ran into the same issue.  
Sorry for the mention, @MichaBrugger . Is this plugin still maintained? 😢

**Comment by MichaBrugger** [comment]
I wish I could tell you something else, but lately I really don't find the time to maintain the plugin. If anyone would like to make PRs or take it over, I'd be more than happy to facilitate that.

**Comment by husjon** [comment]
@MichaBrugger I've prepared a PR to fix this, see #34 

Also, I might be able help maintaining this project if you like, we could have a chat at some point to facilitate this. :)

**Comment by MichaBrugger** [comment]
Thank you very much, @husjon! I'm very happy to hear that :) I merged your PRs und sent you a collab invitation 👍🏼

**Comment by husjon** [comment]
Thanks and yeah, can do
