### ISSUE TITLE
Using the original page (Goodreads link) in a property 

### ISSUE THREAD

**Issue by creativefibro** [MichaBrugger/booksidian_plugin#33]
I have been using the link to the original page within the Content of the book-note section. Is there anyway to add this to the properties instead. As the field is available ie {{id}} I would imagine it would not be too complicated to add it to the 18  existing fields.

I am currently manually moving it from the note to the Property but it would be great if it could arrive in the right place. Thanks

**Comment by dotnvo** [comment]
Yeah I think this would be cool to implement. I think it would be cool to do this in the frontmatter section and allow custom properties that you can specify. The drop down menu can allow you to add the data easily for the premade stuff, but it just throws it in a text box that you can update. this would let you not only do what @creativefibro suggests, but also customize/bend the template to your liking.
