### ISSUE TITLE
booksidian seems to always overwrite content, even if it's disabled

### ISSUE THREAD

**Issue by robomark** [MichaBrugger/booksidian_plugin#46]
I'm running current versions of obsidian and the plugin, and it's consistently overwriting a note when it syncs with goodreads, regardless of how the "overwrite" switch is set. Is there some other debug output I can look at to investigate this?

**Comment by husjon** [comment]
Hi, it seem like the check for the overwrite setting isn't checked when writing the files.
I'll prepare a fix for it a bit later on today.

**Comment by husjon** [comment]
Hi @robomark the fix has been made and will be available in version 0.5.1, releasing shortly.
This issue will be closed as a result.

**Comment by robomark** [comment]
Yup, it's working as expected now with 0.5.1. Thanks!

**Comment by husjon** [comment]
Hi @robomark thanks for the update.
I haven't used the plugin myself since the update but I'll take a look.

**Comment by husjon** [comment]
Found the issue, I had forgotten to add a check for if the file already existed and only then overwrite the content if the user had enabled that setting.
I've pushed a fix for it and it should be available within the hour. :)
