### ISSUE TITLE
Other bookshelves being imported

### ISSUE THREAD

**Issue by creativefibro** [MichaBrugger/booksidian_plugin#8]
I have left my Obsidian settings to just import my currently-reading shelf which has five books in it. However, when I sync'd it there were several imported including to-read shelves and read books. There is a good chance I will want to import all my books but into different areas of my vault depending on the theme etc
<img width="388" alt="CleanShot 2022-07-04 at 2 30 59@2x" src="https://user-images.githubusercontent.com/39191327/177166434-d77ce7ef-b3cd-4fd9-bd78-8797bf4873a7.png">

<img width="273" alt="CleanShot 2022-07-04 at 2 35 16@2x" src="https://user-images.githubusercontent.com/39191327/177166485-75963148-eeba-43b6-b2b1-ab31bdab285b.png">

<img width="950" alt="CleanShot 2022-07-04 at 2 32 21@2x" src="https://user-images.githubusercontent.com/39191327/177166501-a19c1815-4a2c-40b6-b079-d70c677d826d.png">

<img width="290" alt="CleanShot 2022-07-04 at 2 31 29@2x" src="https://user-images.githubusercontent.com/39191327/177166537-ea20a7a3-9985-4239-87d3-6e5e190d90a2.png">

<img width="375" alt="CleanShot 2022-07-04 at 2 33 28@2x" src="https://user-images.githubusercontent.com/39191327/177166532-bc164b22-c16c-4ecf-aaa1-981c258242ed.png">

.

**Comment by creativefibro** [comment]
Apologies, I miss read the instruction and though it was all reference to the shelf that I removed. Having looked at the example I have added "&shelf=" back to the end. There is a good chance another newbie could make the same mistake so hopefully this will help them.

**Comment by MichaBrugger** [comment]
Thanks for bringing it up! I'll make sure to improve the relevant documentation with the next patch 👍🏼

**Comment by hoffination** [comment]
I also ran into this too just this week. Might make the documentation even more explicit. Thanks!
